<div id="loginInfoBox">
    <div>
        <?php if ($params["userParams"]["loggedIn"]): ?>
        <p>Kirjautuneena käyttäjänä:</p>
        <div>
            <h3 id="usernameText">
                <strong><?= $params["userParams"]["username"]?></strong>
            </h3>

            <div>
                <a id="authButton" href="<?= siteUrl("logout") ?>">Kirjaudu ulos</a>
            </div>
        </div>
        <?php else: ?>
        <p>Et ole kirjautunut sisään.</p>
        <div>
            <div>
                <a id="authButton" href="<?= siteUrl("login") ?>">Kirjaudu</a>
            </div>
        </div>
        <?php endif ?>
    </div>
</div>

<div type="button" onclick="activateLoginBox()" id="loginBoxIcon">
    <h2> 👩🏻‍🌾 </h2>
</div>
