<div id="navi">
    <div id="grid_navi">
        <div class="navi_column_1 headline_border">
            <h2>
                <a class="link" href="<?= siteUrl('herbarium') ?>">Kasvilista</a>
            </h2>
        </div>
        <div class="navi_column_2 headline_border">
            <h2>
                <a class="link" href="<?= siteUrl('identification') ?>">Lajintunnistus</a>
            </h2>
        </div>
        <div class="navi_column_3">
            <h2>
                <a class="link" href="<?= siteUrl('other') ?>">Muuta kivaa</a>
            </h2>
        </div>
    </div>
</div>