<div id="navi">
    <div id="grid_navi">
        <div class="navi_column_1 headline_border">
            <h2>
                <a class="link" href="/Nettikasvio/plant_list.php">Kasvilista</a>
            </h2>
        </div>
        <div class="navi_column_2 headline_border">
            <h2>
                <a class="link" href="/Nettikasvio/identification.php">Lajintunnistus</a>
            </h2>
        </div>
        <div class="navi_column_3">
            <h2>
                <a class="link" href="/Nettikasvio/others.php">Muuta kivaa</a>
            </h2>
        </div>
    </div>
</div>