<!DOCTYPE html>
<html>
<?= $snippets["header"] ?>
<?= $snippets["loginBox"] ?>

<body>
    <div id="pageContainer">
        <div class="pageBackground">
            <?= $snippets["pageHeadline"] ?>
            <?= $snippets["navi"] ?>

            <div class="contentArea contentBox">
                <?= $lib["filter"] ?>
                <?= $lib["table"] ?>
            </div>
        </div>
        <?= $snippets["footer"] ?>
    </div>

<script type="text/javascript" src="<?= siteUrl("js/operation.js") ?>"></script>
<script>
    addScrollIcons();
</script>
</body>
</html>
