<div id="loginInfoBox">
    <div>
        <?php if ($params["userParams"]["loggedIn"]): ?>
        <p>Kirjautuneena käyttäjänä:</p>
        <div>
            <h3>
                <strong><?= $params["userParams"]["username"]?></strong>
            </h3>
            <form action="<?= siteUrl("logout") ?>">
                <button id="authButton" type="submit">Kirjaudu ulos</button>
            </form>
        </div>
        <?php else: ?>
        <p>Et ole kirjautunut sisään.</p>
        <div>
            <form action="<?= siteUrl("login") ?>">
                <button id="authButton" type="submit">Kirjaudu</button>
            </form>
        </div>
        <?php endif ?>
    </div>
</div>

<div type="button" onclick="activateLoginBox()" id="loginBoxIcon">
    <h2> 👩🏻‍🌾 </h2>
</div>
