<nav id="navi">
    <div id="gridNavi">
        <div class="naviColumn1">
            <div>
                <a href="<?= siteUrl('herbarium') ?>">Kasvio</a>
            </div>
        </div>
        <div class="naviColumn2">
            <div>
                <a href="<?= siteUrl('identification') ?>">Lajintunnistus</a>
            </div>
        </div>
        <div class="naviColumn3">
            <div>
                <a href="<?= siteUrl('other') ?>">Muuta kivaa</a>
            </div>
        </div>
    </div>
</nav>
