<!DOCTYPE html>
<html>
<?= $snippets["header"] ?>
<body>
    <div class="pageBackground">
        <?= $snippets["pageHeadline"] ?>
        <?= $snippets["navi"] ?>

        <div class="contentArea">
            <div class="textArea">
                <h3 class="description">
                    Hei, olet löytänyt tiesi nettikasvioon! Tämä nettikasvio on vielä materiaalinkeräysvaiheessa, mutta saanee tuulta alleen auringon ja lämmön taas löytäessä tiensä pohjolaan! Tämän sivuston tarkoituksena on auttaa luonnon helmassa kulkevaa samoilijaa tunnistamaan yleisimmät kasvilajit, joita löytää Suomen luonnosta. Sivusto tulee sisältämään seuraavat:
                </h3>
    
                <h4 class="subheadline">
                    Vaiheet:
                </h4>
                <p class="list">
                    <ul>
                        - Kasvien nimet
                    </ul>
                    <ul>
                        - Kuvat kasveista (kameralla taltioitu)
                    </ul>
                    <ul>
                        - Kasvien kukkien väriin perustuva rajaus
                    </ul>
                    <ul>
                        - Nimihaku, joka perustuu kuvien metadatatietoihin
                    </ul>
                    <ul>
                        - Kasviopas lajintunnistukseen ja muuta tietoa kasveista
                    </ul>
                    <ul>
                        - Käyttäjien luonti + kirjautuminen (vain jos käyttäjä lisää kuvia, kaikilla sivun käyttäjillä lukuoikeudet)
                    </ul>
                    <ul>
                        - Kuvien ja lajien lisäys käyttäjällä
                    </ul>
                </p>
                
                <h3 class="description">
                    Tämä sivu ei kuitenkaan juurikaan etene kuvien osalta ennen kuin allekirjoittanut on käynyt kuvaamassa ja tunnistanut kasan kasveja sivua varten. Teen kuitenkin valmiiksi vähän pohjatyötä sivua varten; opiskelen lisää kasveista ja edistän sivun ominaisuuksia. Nyt kasassa on monen kymmenen kasvin kuvat, mutta tärkeitä yleisiä kasveja puuttuu! Tämän sivun luonnonkasvikirjo on ainakin aluksi painottunut hyvinkin paljon Pohjanmaalta löytyviin lajeihin.
                </h3>
            </div>
        </div>
    </div>
<script type="text/javascript" src="<?= siteUrl("js/operation.js") ?>"></script>
</body>
</html>
