<!DOCTYPE html>
<html>
<?= $snippets["header"] ?>
<?= $snippets["loginBox"] ?>

<body>
    <div class="pageBackground">
        <?= $snippets["pageHeadline"] ?>
        <?= $snippets["navi"] ?>

        <div class="contentArea">
            <div class="textArea">
                <?= $lib["loginForm"] ?>
            </div>
        </div>
    </div>
<script type="text/javascript" src="<?= siteUrl("js/operation.js") ?>"></script>
</body>
</html>
