<div id="filter">
    <div>
        <form method="POST" action="<?= siteUrl("herbarium") ?>" id="gridFilter">
            <div class="filterColumn1">
                <input type="text" id="textSearch" name="searchString">
            </div>
            <div class="filterColumn2">
                <select name="colour" class="filterDropdown">
                    <?php
                    echo '<option value="' . null . '" disabled hidden selected>Valitse kukinnon väri</option>';
                    echo '<option value="' . null . '" >ei valintaa</option>';
                    for ($i = 0; $i < $params["filterData"]["coloursCount"]; $i++) {
                        $colour = $params["filterData"]["colours"][$i];
                        echo '<option value="' . $colour . '" >' . $colour . '</option>';
                    } ?>
                </select>
            </div>
            <div class="filterColumn3">
                <select name="type" class="filterDropdown">';
                    <?php
                    echo '<option value="' . null . '" disabled hidden selected>Valitse lajin tyyppi</option>';
                    echo '<option value="' . null . '" >ei valintaa</option>';
                    for ($i = 0; $i < $params["filterData"]["typesCount"]; $i++) {
                        $type = $params["filterData"]["types"][$i];
                        echo '<option value="' . $type . '" >' . $type . '</option>';
                    } ?>
                </select>
            </div>
            <div class="filterColumn4">
                <input type="submit" id="searchButton" name="searchButton" value="Hae kasveja">
            </div>
        </form>
    </div>
</div>
