<?php

$plants = $params["plants"];

if (isset($_GET['error'])) {
    echo '<div class="error">';
    echo    '<h3>Jokin meni vikaan. 🥀</h3>';
    echo '</div>';
}

if ((isset($_GET['success']))) {
    echo '<div class="success">';
    echo    '<h3>Operaatio onnistui. 🌱</h3>';
    echo '</div>';
}

if ($params["userParams"]["loggedIn"] && $params["userParams"]["isAdmin"]) {
    echo    '<div>';
    echo        '<h4 id="adminText"> Jos olet varma kasvihavainnostasi, ja tiedät kasvin nimen, tieteellisen nimen, kasvin tyypin ja värin ja sinulla on kasvista ainakin yksi kuva, voit lisätä kasvin kasvioon.</h4>';
    echo        '<form action="' . siteUrl("herbarium/add-species") . '" class="adminButton">';
    echo            '<input type="submit" id="addSpeciesButton" value="Lisää uusi laji"></input>';
    echo        '</form>';
    echo    '</div>';
}

if (empty($plants)) {
    echo '<div id="plantListText"><h4>Ei lajeja.</h4></div>';

} else {

    if ($params["userParams"]["loggedIn"] && $params["userParams"]["isAdmin"]) {

        echo '<div id="plantList">';
        echo    '<div class="plantListHeadlinesAdmin">';
        echo        '<div class="plantListColumn1"><h4>Lajin nimi</h4></div>';
        echo        '<div class="plantListColumn2"><h4>Tiedot</h4></div>';
        echo        '<div class="plantListColumn3"><h4>Havaintokuvat</h4></div>';
        echo        '<div class="plantListColumn4"><h4>Admin-toiminnot</h4></div>';
        echo    '</div>';

        foreach ($plants as $plant) {
            echo    '<div class="gridPlantListAdmin">';
            echo        '<div class="plantListColumn1">';
            echo            '<p>' . $plant['name'] . '</p>';
            echo        '</div>';
            echo        '<div class="plantListColumn2">';
            echo            '<p>' . $plant['info'] . '</p>';
            echo        '</div>';
            echo        '<div class="plantListColumn3 imageColumn">';
            echo            '<div class="gallery">';
            echo                '<div>';
                                foreach ($plant['images'] as $image) {
                                    $thumbnail = pathinfo($image["src"], PATHINFO_FILENAME) . "-small." . pathinfo($image["src"], PATHINFO_EXTENSION);
            echo                    '<img src="' . siteUrl("plantImg/thumbnails/{$thumbnail}") . '" loading="lazy"' . sprintf(" onclick='enlargeImage(\"%s\")'", siteUrl("plantImg/{$image["src"]}")) . '>';
                                }
            echo                '</div>';
            echo            '</div>';
            echo        '</div>';
            echo        '<div class="plantListColumn4">';
            echo            '<div id="adminFunctionalities">';
            echo                '<div>';
            echo                    '<form method="POST" action="' . siteUrl("herbarium/delete-species/" . $plant['id']) . '"">';
            echo                        '<button class="adminFunctionalityButton" type="submit" name="deleteSpeciesButton">Poista laji</button>';
            echo                    '</form>';
            echo                '</div>';
            echo                '<div>';
            echo                    '<form method="POST" action="' . siteUrl("herbarium/edit-species/" . $plant['id']) . '"">';
            echo                        '<button class="adminFunctionalityButton" type="submit" name="editSpeciesButton">Muokkaa lajia</button>';
            echo                    '</form>';
            echo                '</div>';
            echo            '</div>';
            echo        '</div>';
            echo    '</div>';
        }

    } else {

        echo '<div id="plantList">';
        echo    '<div class="plantListHeadlines">';
        echo        '<div class="plantListColumn1"><h4>Lajin nimi</h4></div>';
        echo        '<div class="plantListColumn2"><h4>Tiedot</h4></div>';
        echo        '<div class="plantListColumn3"><h4>Havaintokuvat</h4></div>';
        echo    '</div>';

        foreach ($plants as $plant) {
            echo    '<div class="gridPlantList">';
            echo        '<div class="plantListColumn1">';
            echo            '<p>' . $plant['name'] . '</p>';
            echo        '</div>';
            echo        '<div class="plantListColumn2">';
            echo            '<p>' . $plant['info'] . '</p>';
            echo        '</div>';
            echo        '<div class="plantListColumn3 imageColumn">';
            echo            '<div class="gallery">';
            echo                '<div>';
                                foreach ($plant['images'] as $image) {
            echo                    '<img src="' . siteUrl("plantImg/{$image["src"]}") . '" loading="lazy"' . sprintf(" onclick='enlargeImage(\"%s\")'", siteUrl("plantImg/{$image["src"]}")) . '>';
                                }
            echo                '</div>';
            echo            '</div>';
            echo        '</div>';
            echo    '</div>';
        }
    }

    echo '</div>';

    echo '<!-- Background for the image enlargement  -->';
    echo '<div id="enlargedImageView" onclick="closeImage()">';
    echo '  <div id="imageBackground"></div>';
    echo '  <div id="enlargedImageContainer">';
    echo '      <img id="enlargedImage"/>';
    echo '  </div>';
    echo '</div>';
    echo '<!---->';
}
