<div class="identificationText">
    <h2>
        Lajintunnistus
    </h2>
    <br>

    <div>
        <h3>
            Alkuarvio
        </h3>
        <div class="textParagraph">
            <p>
                Alkuun kannattaa miettiä esimerkiksi seuraavia asioita:
                <ol>
                    <li>Onko kasvi puu- vai ruohovartinen?</li>
                    <li>Millainen kasvuympäristö on (kostea, kuiva, aurinkoinen, varjoinen, korkeus)?</li>
                    <li>Mistä kasvi löytyi (geologinen sijainti)?</li>
                    <li>Onko kasvissa erityispiirteitä (esim. tuoksu, piikit, kuori, lehden tekstuuri)?</li>
                </ol>
            </p>
        </div>
    </div>

    <div>
        <h3>
            Lehdet
        </h3>
        <div class="textParagraph">
            <div>
                <h4>
                    Lehden osat
                </h4>
                <p>
                    Lehdessä on seuraavat osat:
                    <ol>
                        <li><strong>Kanta tai hanka</strong>, axil</li>
                        <li><strong>Ruoti</strong>, petiole</li>
                        <li><strong>Lapa</strong>, lamina tai blade</li>
                        <li><strong>Lavan tyvi</strong>, base</li>
                        <li><strong>Laita</strong>, margin</li>
                        <li><strong>Kärki</strong>, tip</li>
                        <li><strong>Keskisuoni</strong>, midrib</li>
                        <li><strong>Sivusuoni</strong>, vein</li>
                    </ol>
                </p>
                <figure class="imageArea">
                    <img src="<?= siteUrl("img/leafParts.png") ?>" loading="lazy" onclick="enlargeImage('img/leafParts.png')">
                    <figcaption><strong>Kuva 1: </strong>Lehden osia haavassa.</figcaption>
                </figure>
            </div>
            <div>
                <h4>
                    Lehtien sijoittuminen
                </h4>
                <p>
                    Lehtien sijoittumisella tarkoitetaan tässä sitä, miten lehdet sijoittuvat kasvin varteen nähden. 
                    Lehdet voivat sijoittua seuraavanlaisesti:
                    <ol>
                        <li>Vuorottaisesti: Lehdet kiinnittyneet varteen vastakkaisesti eri tasossa.</li>
                        <li>Vastakkaisesti: Lehdet kiinnittyneet varteen vastakkaisesti samassa tasossa.</li>
                        <li>Kierteisesti: Lehdet kiinnittyneet varteen kiertäen vartta eri tasossa.</li>
                        <li>Säteittäisesti: Lehdet kiinnittyneet säteittäisesti varteen samassa tasossa.</li>
                        <li>Ruusukkeisesti: Lehdet kiinnittyneet säteittäisesti varteen maan tasossa.</li>
                    </ol>
                    Vastakkaisesti sijoittuneita lehtiä esiintyy esim. vaahteroissa, saarneissa, kanukoissa ja Caprifoliacea-heimossa, johon kuuluu mm. heidet, kuusamat ja virmajuuret.
                </p>
                <figure class="imageArea">
                    <img src="<?= siteUrl("img/leafPositions.jpg") ?>" loading="lazy" onclick="enlargeImage('img/leafPositions.jpg')">
                    <figcaption><strong>Kuva 2: </strong>Erilaisia lehtien sijoittumisia varteen nähden.</figcaption>
                </figure>
            </div>
            <div>
                <h4>
                    Lehtien lehdykät
                </h4>
                <p>
                    Lehti voi olla joko yksinkertainen tai kerrannainen. 
                    Yksinkertaisessa lehdessä ruotiin on kiinnittynyt yksi lehti. 
                    Kerrannaislehdessä ruotiin on kiinnittynyt yksi lehti, jossa on useampi lehdykkä (leaflet), ikään kuin lehti kiinni lehdessä. 
                    Tunnistuksessa kannattaakin tarkistaa montako lehdykkää lehdessä on. Kerrannaislehdessä koko lehti tippuu talven tullen.
                    Esimerkiksi pihlajan lehdessä on monta lehdykkää. 
                    Kannattaa huomata, ettei vahingossa sekoita lehtien sijoittumista lehdyköitten sijoittumiseen!
                </p>
            </div>
            <div>
                <h4>
                    Lehtien muoto
                </h4>
                <p>
                    Lehtimuotoja on monenlaisia. Eri lehtimuotoja on kuvattu alla olevassa kuvassa 3 ruudussa I (pois lukien lehtiasennot numeroilla 8, 9, 23, 40 ja kiinnittymistapa numerolla 23).
                    Tässä listattuna muutamia lehtimuotoja:
                    <ol>
                        <li>Neulasmainen (kuvassa numero 1)</li>
                        <li>Sirppimäinen (kuvassa numero 2)</li>
                        <li>Pyöreä (kuvassa numero 3)</li>
                        <li>Vinoneliömäinen (kuvassa numero 4)</li>
                        <li>Puikea (kuvassa numero 7)</li>
                        <li>Sormijakoinen (kuvassa numero 11)</li>
                        <li>Suikea (kuvassa numero 14)</li>
                        <li>Tasasoukka (kuvassa numero 18)</li>
                        <li>Herttamainen (kuvassa numero 21)</li>
                        <li>Parilehdykkäinen (kuvassa numerot 27, 31, 38)</li>
                        <li>Vastapuikea (kuvassa numero 30)</li>
                        <li>Pariliuskainen (kuvassa numero 35)</li>
                        <li>Soikea (kuvassa numero 37)</li>
                    </ol>
                    Tunnistuksessa kannattaa myös kiinnittää huomiota lehtien laitoihin ja suonitukseen. Erilaisia lehtilaitoja ja suonituksia on esitetty kuvassa 3 ruuduissa II ja III.
                </p>
                <figure class="imageArea">
                    <img src="<?= siteUrl("img/leafShapes.png") ?>" loading="lazy" onclick="enlargeImage('img/leafShapes.png')">
                    <figcaption><strong>Kuva 3: </strong>Lehtimuotoja (I), -laitoja (II) ja -suonituskuvioita (III).</figcaption>
                </figure>
            </div>
        </div>

    </div>

    <div>
        <h3>
            Kukat
        </h3>
        <div class="textParagraph">
            <div>
                <h4>
                    Kukan osat
                </h4>
                <p>
                    Kasvin kukat voivat olla yksittäisiä kukkia, kukintoja tai norkkoja. Kukissa on seuraavat osat:
                    <ol>
                        <li><strong>Terälehti</strong>, petal</li>
                        <li><strong>Verholehti</strong>, sepal</li>
                        <li><strong>Hede</strong>, stamen (osina <strong>ponsi</strong>, anther, ja <strong>palho</strong>, filament)</li>
                        <li><strong>Emi</strong>, pistil (osina <strong>luotti</strong>, stigma, <strong>vartalo</strong>, style ja <strong>sikiäin</strong>, ovary)</li>
                        <li><strong>Kukkapohjus</strong>, receptacle</li>
                        <li><strong>Siemenaihe</strong>, ovule</li>
                    </ol>
                    Terälehdet yhdessä muodostavat kukan teriön (corolla) ja verholehdet verhiön (calyx). 
                    Teriö ja verhiö yhdessä muodostavat kehälehdet (tepal). 
                    Tunnistuksessa kannataa kiinnittää huomiota terälehtien, verholehtien, heteiden ja emien lukumäärään, teriön symmetriaan ja kukkien muotoon (esim. huulimainen, perhomainen tai kellomainen). 
                    Joskus terälehdet voivat olla osittain tai kokonaan yhteenkasvaneita tai päällekäisiä ja joskus ne voivat puuttua kokonaan.
                </p>
                <figure class="imageArea">
                    <img src="<?= siteUrl("img/flowerSection.png") ?>" loading="lazy" onclick="enlargeImage('img/flowerSection.png')">
                    <figcaption><strong>Kuva 4: </strong>Kukan läpileikkaus ja osat.</figcaption>
                </figure>
                <figure class="imageArea">
                    <img src="<?= siteUrl("img/flowerParts.png") ?>" loading="lazy" onclick="enlargeImage('img/flowerParts.png')">
                    <figcaption><strong>Kuva 5: </strong>Kukan osia lehtosinilatvassa.</figcaption>
                </figure>
            </div>
            <div>
                <h4>
                    Siemen ja hedelmä
                </h4>
                <p>
                    Kukassa kehittyy kasvin siemenet sisältävä hedelmä. 
                    Ulkonäöllisesti kasvin hedelmät voivat olla esimerkiksi marjoja, pähkinöitä, palkoja tai hedelmiä. 
                    Jos hedelmän keskeltä löytyy kova sisus eli ns. kivi, kyseessä on luumarja.
                    Siemenillä voi olla siivekkeet tai karvat, jotka auttavat niitä leviämään.
                </p>
            </div>
        </div>
    </div>

    <div>
        <h3>
            Varsi ja juuret
        </h3>
        <div class="textParagraph">
            <div>
                <h4>
                    Yleisesti
                </h4>
                <p>
                    Kasvin maanpäällistä osaa kutsutaan versoksi ja maanalaista osaa juuristoksi. 
                    Versoon kuuluvat varsi, lehdet ja kukinnot. 
                    Juuristossa on pääjuuri ja sivujuuret.
                </p>
                <h4>
                    Ruohovartiset kasvit
                </h4>
                <p>
                    Varressa voi olla oksia, lehden kiinnittymiskohtia eli niveliä, ja lehtihankoja, joista lähtee hankasilmuja. 
                    Verson kärjestä löytyy kärkisilmu.
                    Kukat ovat aluksi nupussa, ja niiden juuresta voi löytyä pieniä esilehtiä. 
                    Kasvin vartta suojaa yleensä vahamainen, vettä hylkivä pinta, jota kutsutaan kutikulaksi.
                </p>
                <h4>
                    Puuvartiset kasvit
                </h4>
                <p>
                    Puuvartisilla kasveilla, kuten puilla ja pensailla ei ole kutikulaa. 
                    Sen sijaan varren ulointa kerrosta kutsutaan ulkokuoreksi eli kaarnaksi, jonka alla on sisäkuori eli nila. 
                    Nilan alla on jälsi ja rungon läpileikkauksen keskipiste on ydin. 
                    Puun iän voi laskea vuosirenkaista.
                </p>
            </div>
        </div>
    </div>

    <br>
    <div>
        <h3>
            Lähteet
        </h3>
        <div class="textParagraph">
            <a href="https://opentextbc.ca/plantidentification/chapter/plant-morphology-leaves/">https://opentextbc.ca/plantidentification/chapter/plant-morphology-leaves/</a>
            <br>
            <a href="https://www.youtube.com/watch?v=-XwyLVqKRRQ&t=2560s">https://www.youtube.com/watch?v=-XwyLVqKRRQ&t=2560s</a>
            <br>
            <a href="https://commons.wikimedia.org/wiki/File:Mature_flower_diagram.svg">https://commons.wikimedia.org/wiki/File:Mature_flower_diagram.svg</a>
            <br>
            <a href="https://fi.wikipedia.org/wiki/Lehti_%28kasvitiede%29">https://fi.wikipedia.org/wiki/Lehti_%28kasvitiede%29</a>
            <br>
            <a href="https://peda.net/oppimateriaalit/e-oppi/verkkokauppa/yl%C3%A4koulu/lukuvuosi-20-21/e7el2/ebiologia-727/vesikasvit/teht%C3%A4v%C3%A4t2/kt2">https://peda.net/oppimateriaalit/e-oppi/verkkokauppa/yl%C3%A4koulu/lukuvuosi-20-21/e7el2/ebiologia-727/vesikasvit/teht%C3%A4v%C3%A4t2/kt2</a>
            <br>
            <a href="https://commons.wikimedia.org/wiki/File:Leaf_morphology_numbered.png">https://commons.wikimedia.org/wiki/File:Leaf_morphology_numbered.png</a>
        </div>
    </div>
</div>
<!-- Background for the image enlargement  -->
<div id="enlargedImageView" onclick="closeImage()">
    <div id="imageBackground"></div>
    <div id="enlargedImageContainer">
        <img id="enlargedImage"/>
    </div>
</div>
<!---->
