<!DOCTYPE html>
<html>
<?= $snippets["header"] ?>
<?= $snippets["loginBox"] ?>

<body>
    <div id="pageContainer">
        <div>
            <?= $snippets["pageHeadline"] ?>
            <?= $snippets["navi"] ?>
    
            <div class="contentArea">
                <div class="textArea">
                    <p>401: Sivulle pääsy kielletty 🚫</p>
                </div>
            </div>
        </div>
        <?= $snippets["footer"] ?>
    </div>

<script type="text/javascript" src="<?= siteUrl("js/operation.js") ?>"></script>
</body>
</html>
