<form method="POST" action="<?= siteUrl('herbarium/update-species/' . $params["speciesData"]["id"]) ?>" enctype="multipart/form-data">
    <div class="addContainer">

        <!-- Response -->
        <?php if(isset($_GET['success'])): ?>
        <div class="success">
            <h3>Kasvin muokkaus onnistui. 🌱</h3>
        </div>
        <?php endif ?>
        <?php if(isset($_GET['error'])): ?>
        <div class="error">
            <h3>Muokkaus epäonnistui. 🥀</h3>
            <p>Kokeile käyttää kuville eri tiedostonimeä.</p>
        </div>
        <?php endif ?>
        <!---->

        <div>
            <label for="speciesName">Lajin nimi:</label>
            <div><input type="text" id="speciesName" name="speciesName" value="<?= $params["speciesData"]["name"] ?>" required></div>
        </div>
        <div>
            <label for="speciesDesc">Lajin tiedot:</label>
            <div><textarea type="text" id="speciesDesc" name="speciesDesc"><?= $params["speciesData"]["info"] ?></textarea></div>
        </div>

        <fieldset>
            <legend>Lajin tyyppi:</legend>
            <div>
            <?php
            for ($i = 0; $i < $params["plantData"]["typesCount"]; $i++) {
                $type = $params["plantData"]["types"][$i];
                if ($type == $params["speciesData"]["type"]) {
                    $checked = " checked";
                } else {
                    $checked = "";
                }
                echo '<div>';
                echo    '<input type="radio" id="' . "type{$i}" . '" name="speciesType" value="' . $type . '" required' . $checked . '>';
                echo    '<label for="' . "type{$i}" . '">' . $type . '</label>';
                echo '</div>';
            } ?>
            </div>
        </fieldset>

        <fieldset>
            <legend>Lajin väri:</legend>
            <div>
            <?php
            for ($i = 0; $i < $params["plantData"]["coloursCount"]; $i++) {
                $colour = $params["plantData"]["colours"][$i];
                if (in_array($colour, $params["speciesData"]["colours"])) {
                    $checked = " checked";
                } else {
                    $checked = "";
                }
                echo '<div>';
                echo    '<input type="checkbox" id="' . "colour{$i}" . '" name="speciesColour[]" value="' . $colour . '"' . $checked . '>';
                echo    '<label for="' . "colour{$i}" . '">' . $colour . '</label>';
                echo '</div>';
            } ?>
            </div>
        </fieldset>

        <!-- Images -->
        <fieldset>
            <legend>Kuvat:</legend>
            <div id="imageNotice">
                <p>Nykyään kasville löytyy seuraavan nimiset kuvatiedostot:</p>
                <?php
                echo '<div>';
                foreach ($params["speciesData"]["images"] as $image) {
                    echo '<div>';
                    echo    '<input type="checkbox" id="' . $image . '" name="speciesImages[]" value="' . $image . '" checked>';
                    echo    '<label for="' . $image . '">' . $image . '</label>';
                    echo '</div>';
                }
                echo '</div>';
                ?>
                <p>Jos haluat säilyttää vanhat kuvat, pidä kuvatiedostot ruksittuna. Voit lisätä lisää kuvia alta. Kuvia on kuitenkin oltava ainakin yksi.</p>
            </div>
            <table id="imagesForm">
                <thead>
                    <tr>
                        <!-- Labels for image data -->
                        <th scope="col">Kuvatiedosto: (.jpg/.png/.jpeg)</th>
                        <!---->
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <!-- Input fields for image data -->
                        <td data-label="Kuvatiedosto:   (.jpg/.png/.jpeg)" scope="row"><input type="file" name="images[0]"></td>
                        <!---->
                        <!-- Add more images button -->
                        <td id="buttonBox"><input type="button" class="imageButton" onclick="addImage()" id="addImageButton" name="addImageButton" value="Lisää"></td>
                        <!---->
                    </tr>
                </tbody>
            </table>
        </fieldset>
        <!---->

        <div id="addArea">
            <div>
                <button type="submit" id="editSpeciesButton" name="editSpeciesButton">Muokkaa lajia</button>
            </div>
        </div>
    </div>
</form>
