<div id="filter">
    <div>
        <form method="POST" action="search.php" id="gridFilter">
            <div class="filterColumn_1">
                <input type="text" id="textSearch" name="searchString" value= <?= $params["sessionParams"]["searchString"] ?> >
            </div>
            <div class="filterColumn2">
                <select name="colour" class="filterDropdown">
                    <?php
                    // get colour filter list length and enumerate colours
                    $colour = null;
                    $selectedColour = $colour == $params["sessionParams"]["colour"];
                    ?>
                    <option value= <?= $colour . "\"" . $selectedColour ?> disabled hidden selected>Valitse kasvin väri</option>
                    <option value= <?= $colour . "\"" . $selectedColour ?> >Ei valintaa</option>
                    <?php
                    for ($i = 0; $i < $colour_and_type_lengths[0]; $i++) {
                        $colour = getColourName($i);
                        $selectedColour = $colour == $params["sessionParams"]["colour"];
                    ?>
                    <option value= <?= $colour . "\"" . $selectedColour ?> ><?= $colour ?></option>
                    <?php } ?>
                </select>
            </div>
            <div class="filterColumn3">
                <select name="type" class="filterDropdown">';
                    <?php
                    // get type filter list length and enumerate colours
                    $type = null;
                    $selectedType = $type == $params["sessionParams"]["type"];
                    ?>
                    <option value= <?= $type . "\"" . $selectedType ?> disabled hidden selected>Valitse kasvin tyyppi</option>
                    <option value= <?= $type . "\"" . $selectedType ?> >Ei valintaa</option>
                    <?php
                    for ($i = 0; $i < $colour_and_type_lengths[1]; $i++) {
                        $type = getTypeName($i);
                        $selectedType = $type == $params["sessionParams"]["type"];
                    ?>
                    <option value= <?= $colour . "\"" . $selectedColour ?> ><?= $type ?></option>
                    <?php } ?>
                </select>
            </div>
            <div class="filterColumn4">
                <input type="submit" id="searchButton" name="searchButton" value="Hae kasveja">
            </div>
        </form>
    </div>
</div>