<?php

$plants = $params["plants"];

if (empty($plants)) {
    echo '<p class="plant_list_column_2">Ei kasveja.</p>';
} else {
    echo '<div id="plant_list">';
    echo    '<div id="grid_plant_list">';
    echo        '<h4 class="plant_list_column_1">Kasvin nimi</h4>';
    echo        '<h4 class="plant_list_column_2">Tiedot</h4>';
    echo        '<h4 class="plant_list_column_3">Havaintokuvat</h4>';
    echo    '</div>';
    echo '</div>';

    foreach ($plants as $plant) {
        echo '<div id="plant_list">';
        echo    '<div id="grid_plant_list">';
        echo        '<div class="plant_list_column_1 headline_border">';
        echo            '<p>' . $plant['name'] . '</p>';
        echo        '</div>';
        echo        '<div class="plant_list_column_2 headline_border">';
        echo            '<p>' . $plant['info'] . '</p>';
        echo        '</div>';
        echo        '<div class="plant_list_column_3">';
        echo            '<p>' . $plant['image'] . '</p>';
        echo        '</div>';
        echo    '</div>';
        echo '</div>';
    }
}
