<?php

$plants = $params["plants"];

if ($params["userParams"]["loggedIn"] && $params["userParams"]["isAdmin"]) {
    echo    '<div class="adminArea">';
    echo        '<h4> Jos olet varma kasvihavainnostasi, ja tiedät kasvin nimen, tieteellisen nimen, kasvin tyypin ja värin ja sinulla on kasvista ainakin yksi kuva, voit lisätä kasvin kasvioon.</h4>';
    echo        '<div class="adminButton">';
    echo            '<button id="addSpeciesButton" href="' . siteUrl("herbarium/add-species") . '">Lisää uusi laji</button>';
    echo        '</div>';
    echo    '</div>';
}

if (empty($plants)) {
    echo '<div><h4>Ei lajeja.</h4></div>';

} else {

    if ($params["userParams"]["loggedIn"] && $params["userParams"]["isAdmin"]) {

        echo '<div id="plantList">';
        echo    '<div id="gridPlantListAdmin">';
        echo        '<div class="plantListColumn1"><h4>Lajin nimi</h4></div>';
        echo        '<div class="plantListColumn2"><h4>Tiedot</h4></div>';
        echo        '<div class="plantListColumn3"><h4>Havaintokuvat</h4></div>';
        echo        '<div class="plantListColumn4"><h4>Admin-toiminnot</h4></div>';
        echo    '</div>';

        foreach ($plants as $plant) {
            echo    '<div id="gridPlantListAdmin">';
            echo        '<div class="plantListColumn1">';
            echo            '<p>' . $plant['name'] . '</p>';
            echo        '</div>';
            echo        '<div class="plantListColumn2">';
            echo            '<p>' . $plant['info'] . '</p>';
            echo        '</div>';
            echo        '<div class="plantListColumn3 imageColumn">';
            echo            '<div class="gallery">';
            echo                '<div>';
                                foreach ($plant['images'] as $image) {
            echo                    '<img src="' . siteUrl("plantImg/{$image["src"]}") . '" loading="lazy"' . sprintf(" onclick='enlargeImage(\"%s\")'", siteUrl("plantImg/{$image["src"]}")) . '>';
                                }
            echo                '</div>';
            echo            '</div>';
            echo        '</div>';
            echo        '<div class="plantListColumn4">';
            echo            '<div id="adminFunctionalities">';
            echo                '<div>';
            echo                    '<form method="POST" action="' . siteUrl('herbarium/delete-species/' . $plant['id']) . '"">';
            echo                        '<button class="adminFunctionalityButton" type="submit" name="deletePlant" class="deletePlantButton">Poista laji</button>';
            echo                    '</form>';
            echo                '</div>';
            echo                '<div>';
            echo                    '<button class="adminFunctionalityButton" href="' . siteUrl("herbarium/edit-species") . '">Muokkaa lajia</button>';
            echo                '</div>';
            echo            '</div>';
            echo        '</div>';
            echo    '</div>';
        }

    } else {

        echo '<div id="plantList">';
        echo    '<div id="gridPlantList">';
        echo        '<div class="plantListColumn1"><h4>Lajin nimi</h4></div>';
        echo        '<div class="plantListColumn2"><h4>Tiedot</h4></div>';
        echo        '<div class="plantListColumn3"><h4>Havaintokuvat</h4></div>';
        echo    '</div>';

        foreach ($plants as $plant) {
            echo    '<div id="gridPlantList">';
            echo        '<div class="plantListColumn1">';
            echo            '<p>' . $plant['name'] . '</p>';
            echo        '</div>';
            echo        '<div class="plantListColumn2">';
            echo            '<p>' . $plant['info'] . '</p>';
            echo        '</div>';
            echo        '<div class="plantListColumn3 imageColumn">';
            echo            '<div class="gallery">';
            echo                '<div>';
                                foreach ($plant['images'] as $image) {
            echo                    '<img src="' . siteUrl("plantImg/{$image["src"]}") . '" loading="lazy"' . sprintf(" onclick='enlargeImage(\"%s\")'", siteUrl("plantImg/{$image["src"]}")) . '>';
                                }
            echo                '</div>';
            echo            '</div>';
            echo        '</div>';
            echo    '</div>';
        }
    }

    echo '</div>';

    echo '<!-- Background for the image enlargement  -->';
    echo '<div id="enlargedImageView" onclick="closeImage()">';
    echo '  <div id="imageBackground"></div>';
    echo '  <div id="enlargedImageContainer">';
    echo '      <img id="enlargedImage"/>';
    echo '  </div>';
    echo '</div>';
    echo '<!---->';
}
